# Project: AST_Project
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = obj/AST_Project_private.res
OBJ  = obj/ast.o $(RES)
LINKOBJ  = obj/ast.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -static-libgcc  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = bin/AST.exe
CXXFLAGS = $(CXXINCS)   -std=c99
CFLAGS = $(INCS)   -std=c99
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before bin/AST.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "bin\AST.exe" $(LIBS)

obj/ast.o: src/ast.c
	$(CC) -c src/ast.c -o obj/ast.o $(CFLAGS)

obj/AST_Project_private.res: AST_Project_private.rc 
	$(WINDRES) -i AST_Project_private.rc --input-format=rc -o obj/AST_Project_private.res -O coff 
